---
- name: Tomcat deployment playbook
  hosts: "{{ hosts }}"
  become: yes
  become_method: sudo
  vars:
    tomcat_ver: 9.0.33
    ui_manager_user: passedasvar
    ui_manager_pass: passedasvar
    ui_admin_username: passedasvar
    ui_admin_pass: passedasvar
  roles:
    - tomcat
